### ISSUE TITLE
Not working on live website

### ISSUE THREAD

**Issue by Ejayz** [Thunder33345/DiscordHook#3] opened 2020-08-25 13:56 UTC
I cant send webhooks from my website and echo this return statement 
-----Local Host------
Array ( [sent] => Array ( [array] => Array ( [username] => Recent Claim Sent Anouncer [content] => hello ) [json] => {"username":"Recent Claim Sent Anouncer","content":"hello"} ) [http_code] => 204 [headers] => Array ( [http_code] => HTTP/2 204 [date] => Tue, 25 Aug 2020 13:51:02 GMT [set_cookie] => __cfduid=d6c1fe260b1a41254df2b29e129b9cf621598363462; expires=Thu, 24-Sep-20 13:51:02 GMT; path=/; domain=.discordapp.com; HttpOnly; SameSite=Lax [strict_transport_security] => max-age=31536000; includeSubDomains [x_ratelimit_bucket] => 3cd1f278bd0ecaf11e0d2391374c011d [x_ratelimit_limit] => 5 [x_ratelimit_remaining] => 4 [x_ratelimit_reset] => 1598363465 [x_ratelimit_reset_after] => 2 [x_envoy_upstream_service_time] => 35 [via] => 1.1 google [cf_cache_status] => DYNAMIC [cf_request_id] => 04c77c04570000124cc5092200000001 [expect_ct] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" [server] => cloudflare [cf_ray] => 5c85c91a2d33124c-HKG ) [json] => [raw] => )

-----Website------
Array ( [sent] => Array ( [array] => Array ( [username] => Recent Claim Sent Anouncer [content] => New claim has been sent! ADDRESS:0x61c0fa8ef4c27357564de51747841851be8c4c55 BLOCKCHAIN SCANNER LINK: AMOUNT:0.0005 CoroEx Coin.Please check block chain Scanner link to confirm the transaction! ) [json] => {"username":"Recent Claim Sent Anouncer","content":"New claim has been sent! ADDRESS:0x61c0fa8ef4c27357564de51747841851be8c4c55\n BLOCKCHAIN SCANNER LINK: \n AMOUNT:0.0005 CoroEx Coin.Please check block chain Scanner link to confirm the transaction!"} ) [http_code] => [headers] => Array ( [http_code] => ) [json] => [raw] => ) 

unlike in local host it appears that the website is not sending anything.Can you help out fixing?
thanks

**Comment by Thunder33345** [comment] 2020-09-24 11:45
Duplicate of #2

**Closed as completed by Thunder33345** 2020-09-24 11:45 UTC
